// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsyQWljZZySry08QL9F7vir8LwCKsJ3Xo',
    appId: '1:1043759854540:web:d5748fbde3d924363ea369',
    messagingSenderId: '1043759854540',
    projectId: 'cmsc23-todo-app-rglandicho',
    authDomain: 'cmsc23-todo-app-rglandicho.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-rglandicho.appspot.com',
    measurementId: 'G-NM1PK8J5NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qon5AkMhMANLYtD-V0gYcN8GdrDlA8U',
    appId: '1:1043759854540:android:14cb7ae8e308bf0a3ea369',
    messagingSenderId: '1043759854540',
    projectId: 'cmsc23-todo-app-rglandicho',
    storageBucket: 'cmsc23-todo-app-rglandicho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBmyZxHZySv9CJisXGsyoiM3MZA_6ynik',
    appId: '1:1043759854540:ios:e634916ef78376d33ea369',
    messagingSenderId: '1043759854540',
    projectId: 'cmsc23-todo-app-rglandicho',
    storageBucket: 'cmsc23-todo-app-rglandicho.appspot.com',
    iosClientId: '1043759854540-itb6ba7860qp14rt96utr68iaim8oge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBmyZxHZySv9CJisXGsyoiM3MZA_6ynik',
    appId: '1:1043759854540:ios:e634916ef78376d33ea369',
    messagingSenderId: '1043759854540',
    projectId: 'cmsc23-todo-app-rglandicho',
    storageBucket: 'cmsc23-todo-app-rglandicho.appspot.com',
    iosClientId: '1043759854540-itb6ba7860qp14rt96utr68iaim8oge6.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
